server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB

    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # swagger

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://IP:3306/portal?serverTimezone=Asia/Seoul
#    username:
#    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.H2Dialect, org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# jwt
app:
  jwtSecret: vitasoftvitasoftvitasoftvitasoftvitasoftvitasoftvitasoftvitasoftvitasoftvitasoft # 64
  jwtExpirationMs: 3600000